### ISSUE TITLE
Use BeautifulSoup over lxml

### ISSUE THREAD

**Issue by kalbhor** [schollz/playlistfromsong#4]
BeautifulSoup can achieve the same things as lxml and do a lot more. This will reduce 1 manual dependency too. May I try and send a pull request?

**Comment by schollz** [comment]
Yes. I like lxml because it is fast, but here that doesn't matter. I would like to switch it also because lxml is tricky to install on windows. Go ahead!

**Comment by schollz** [comment]
Added in https://github.com/schollz/playlistfromsong/commit/5a3ed802e77f6e58afc840df9d044fa03a332a67
