### ISSUE TITLE
Doesn't work in Python2

### ISSUE THREAD

**Issue by kabirvirji** [schollz/playlistfromsong#8]
After installing all dependencies on Mac, I'm running into an issue.

`playlistfromsong --song 'Miles Davis Blue In Green' --num 5`

When I run this command I'm getting this error:

```
usage: playlistfromsong [-h] [-s SONG] [-n NUM] [-b BEARER] {config} ...
playlistfromsong: error: too few arguments
```

Is there something I'm missing?

**Comment by schollz** [comment]
Yeah, its a Python version problem! Its no longer Python2 compatible, you'll have to install via Python3.
You can do:

```
python -m pip uninstall playlistfromsong
python3 -m pip install playlistfromsong
```

**Comment by kabirvirji** [comment]
Got it working, thanks!

I uninstalled successfully like that, but I wasn't able to install with:

`python3 -m pip install playlistfromsong`

I had to cd to:

`/usr/local/lib/python3.6/site-packages/pip`

and then:

`python3 __main__.py install playlistfromsong`

I think it had some weirdness to do with my own Python / pip setup

**Comment by rachmadaniHaryono** [comment]
@schollz maybe add python3 badge on project readme?

e:

![python3.3+](https://img.shields.io/badge/python-3.3%2B-brightgreen.svg)

code

    ![python3.3+](https://img.shields.io/badge/python-3.3%2B-brightgreen.svg)

e2: i will make pr for this.
